require "rspec/matchers/dm/has_property"
require "rspec/matchers/dm/belongs_to"
require "rspec/matchers/dm/has_many"
require "rspec/matchers/dm/has_one"
#require "spec/matchers/dm/has_and_belongs_to_many"
#require "spec/matchers/dm/has_timestamps"